# Generated by Django 6.0.1 on 2026-01-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. MBBS, MD (Cardiology)', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, help_text='Average patient rating out of 5', max_digits=2),
        ),
        migrations.AddField(
            model_name='hospital',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the hospital was established', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(blank=True, help_text='e.g. Multispeciality, Cardiac Center, Children’s Hospital', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional hero/cover image shown on the hospital detail page'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialties_offered',
            field=models.CharField(blank=True, help_text='Comma-separated list of key specialties (Cardiology, Neurology, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='form',
            field=models.CharField(blank=True, help_text='e.g. Tablet, Syrup, Injection', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image for advanced medicine cards'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pack_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of units (e.g. tablets) per pack'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 500 mg, 5 mg/ml', max_length=50),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicine')),
            ],
            options={
                'unique_together': {('cart', 'medicine')},
            },
        ),
    ]
