# Generated by Django 6.0.1 on 2026-01-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_oxygen_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
