# Generated by Django 6.0.1 on 2026-01-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_medicineorder_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('HOSPITAL_ADMIN', 'Hospital Admin'), ('PHARMACY_ADMIN', 'Pharmacy Admin'), ('OXYGEN_SUPPLIER', 'Oxygen Supplier'), ('ADMIN', 'Platform Admin')], default='PATIENT', max_length=20),
        ),
    ]
