# Generated by Django 6.0.1 on 2026-01-30 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.TimeField(help_text='Expected arrival time')),
                ('payment_option', models.CharField(choices=[('CASH', 'Cash at Hospital'), ('INSURANCE', 'Insurance / TPA'), ('ONLINE', 'Online Payment')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.hospitalbed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
