# Generated by Django 6.0.1 on 2026-01-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bedbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygenbooking',
            name='payment_option',
            field=models.CharField(choices=[('CASH', 'Cash on Delivery / Pickup'), ('INSURANCE', 'Insurance / TPA'), ('ONLINE', 'Online Payment')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='oxygenbooking',
            name='time_slot',
            field=models.TimeField(blank=True, help_text='Expected delivery/pickup time', null=True),
        ),
    ]
